### ISSUE TITLE
look through the floor

### ISSUE THREAD

**Issue by nudelauflauch** [Affehund/BetterPanoramas#1]
if I make new panorama it is always in the floor

**Comment by Affehund** [comment]
Can you please provide a screenshot of how it looks like and from where you made the screenshot? Sometimes it happens that it is in the floor / wall if you are to near to them.

**Comment by nudelauflauch** [comment]
this is the paorama 
![panorama_1](https://user-images.githubusercontent.com/76126544/117330361-e5946580-ae95-11eb-9831-8de759cad968.png)
![panorama_2](https://user-images.githubusercontent.com/76126544/117330370-e7f6bf80-ae95-11eb-8e81-08cdd69764a2.png)
![panorama_3](https://user-images.githubusercontent.com/76126544/117330384-eb8a4680-ae95-11eb-8224-fcd224c5d55b.png)
![panorama_4](https://user-images.githubusercontent.com/76126544/117330399-efb66400-ae95-11eb-9e18-ece8bdc9a3a2.png)
![panorama_5](https://user-images.githubusercontent.com/76126544/117330405-f1802780-ae95-11eb-9859-950a8792a8e0.png)
![panorama_0](https://user-images.githubusercontent.com/76126544/117330410-f218be00-ae95-11eb-8076-8599e9a26958.png)
and this is were I made it
![2021-05-06_18 07 09](https://user-images.githubusercontent.com/76126544/117330519-12487d00-ae96-11eb-88a2-c25175fcbb66.png)

**Comment by Affehund** [comment]
Yeah, kind a weird. But it should definitely work if you stand some blocks above your position.
